#!/bin/bash
# ═══════════════════════════════════════════
# The Agency — Convert Agents for Cursor
# Converts .md profiles → Cursor .cursorrules format
# Usage: ./scripts/install-cursor.sh [output-dir]
# ═══════════════════════════════════════════

set -e

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="${1:-$SOURCE_DIR/cursor-export}"

echo ""
echo "╔══════════════════════════════════════╗"
echo "║     THE AGENCY — Cursor Export       ║"
echo "╚══════════════════════════════════════╝"
echo ""

mkdir -p "$OUTPUT_DIR"

converted=0

while IFS= read -r -d '' agent_file; do
  division=$(basename "$(dirname "$agent_file")")
  agent_name=$(basename "$agent_file" .md)
  output_file="$OUTPUT_DIR/${division}-${agent_name}.cursorrules"

  # Extract codename from the agent file
  codename=$(grep -m1 "\*\*Codename:\*\*" "$agent_file" | sed 's/.*\*\*Codename:\*\* //')

  {
    echo "# Cursor Rules — The Agency"
    echo "# Agent: $agent_name | Division: $division | Codename: $codename"
    echo "# Auto-generated by install-cursor.sh"
    echo ""
    echo "## Persona"
    echo ""
    # Extract the Identity section
    awk '/^## Identity/,/^## [A-Z]/' "$agent_file" | grep -v "^## [A-Z][a-z]" | tail -n +2
    echo ""
    echo "## Core Skills"
    echo ""
    awk '/^## Core Skills/,/^## [A-Z]/' "$agent_file" | grep -v "^## [A-Z][a-z]" | tail -n +2
    echo ""
    echo "## Rules"
    echo ""
    awk '/^## Kill Conditions/,0' "$agent_file" | tail -n +2
  } > "$output_file"

  echo "  ✓ CONVERTED $division/$agent_name → cursor-export/"
  ((converted++))

done < <(find "$SOURCE_DIR" -path "$SOURCE_DIR/scripts" -prune -o \
  -path "$SOURCE_DIR/cursor-export" -prune -o \
  -name "*.md" ! -name "README.md" -print0)

echo ""
echo "────────────────────────────────────────"
echo "  Converted: $converted agents"
echo "  Output:    $OUTPUT_DIR"
echo "────────────────────────────────────────"
echo ""
echo "  To use in Cursor:"
echo "  1. Copy the .cursorrules file to your project root"
echo "  2. Rename to .cursorrules"
echo "  3. Open Cursor — the agent persona is now active"
echo ""
